**NAME:SHRAVYA SHASHIDHAR      
GITHUB USERNAME:shravya2490             
USCID:sshashid**

In [1]:
import pandas as pd
from scipy.stats import bootstrap
import numpy as np

(a)Download the AReM data

**The data is stored in the data folder. The extra comma in cycling data, dataset9 and dataset14 was manually removed using excel and the dataset4 in bending 2 folder is corrected using excel.**

(b)Keep datasets 1 and 2 in folders bending1 and bending 2, as well as datasets 1,
2, and 3 in other folders as test data and other datasets as train data

In [2]:

test=list()
train=list()

def data_seperation(total_number, for_testing, activity):
    test_ending=for_testing+1
    testing_data=list()
    training_data=list()
    for i in range(1,test_ending):
        pathToChoose='../data/AReM/'+activity+'/dataset'+str(i)+'.csv'
        df=pd.read_csv(pathToChoose, usecols=range(7), skiprows = 4)
        testing_data.append(df)
    final_test_data=pd.concat(testing_data,ignore_index=True)
    for k in range(test_ending,total_number+1):
        pathToChoose='../data/AReM/'+activity+'/dataset'+str(k)+'.csv'
        df=pd.read_csv(pathToChoose, usecols=range(7), skiprows = 4)
        training_data.append(df)
    final_training_data=pd.concat(training_data,ignore_index=True)

    return final_test_data,final_training_data

bending1_data_seperation=data_seperation(7,2,'bending1')
bending2_data_seperation=data_seperation(6,2,'bending2')
cycling_data_seperation=data_seperation(15,3,'cycling')
lying_data_seperation=data_seperation(15,3,'lying')
sitting_data_seperation=data_seperation(15,3,'sitting')
standing_data_seperation=data_seperation(15,3,'standing')
walking_data_seperation=data_seperation(15,3,'walking')

test.append(bending1_data_seperation[0])
test.append(bending2_data_seperation[0])
test.append(cycling_data_seperation[0])
test.append(lying_data_seperation[0])
test.append(sitting_data_seperation[0])
test.append(standing_data_seperation[0])
test.append(walking_data_seperation[0])

train.append(bending1_data_seperation[1])
train.append(bending2_data_seperation[1])
train.append(cycling_data_seperation[1])
train.append(lying_data_seperation[1])
train.append(sitting_data_seperation[1])
train.append(standing_data_seperation[1])
train.append(walking_data_seperation[1])

testData=pd.concat(test,ignore_index=True)
trainData=pd.concat(train,ignore_index=True)

print(testData)
print(trainData)

      # Columns: time  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0                   0      39.25       0.43      22.75       0.43      33.75
1                 250      39.25       0.43      23.00       0.00      33.00
2                 500      39.25       0.43      23.25       0.43      33.00
3                 750      39.50       0.50      23.00       0.71      33.00
4                1000      39.50       0.50      24.00       0.00      33.00
...               ...        ...        ...        ...        ...        ...
9115           118750      36.00       2.45      17.00       5.10      20.50
9116           119000      34.33       1.89      15.00       2.45      17.00
9117           119250      33.00       7.35      14.60       3.14      13.00
9118           119500      31.67       1.25      11.00       6.16      19.25
9119           119750      30.75      10.21      11.75       1.09      18.50

      var_rss23
0          1.30
1          0.00
2          0.00
3          0.00
4          0.00
...         ...
9115       0.87
9116       2.12
9117       5.70
9118       2.17
9119       3.20

[9120 rows x 7 columns]
       # Columns: time  avg_rss12  var_rss12  avg_rss13  var_rss13  avg_rss23  \
0                    0      42.00       0.71      21.25       0.43      30.00
1                  250      41.50       0.50      20.25       1.48      31.25
2                  500      41.50       0.50      14.25       1.92      33.00
3                  750      40.75       0.83      15.75       0.43      33.00
4                 1000      40.00       0.71      20.00       2.74      32.75
...                ...        ...        ...        ...        ...        ...
33114           118750      34.50       6.18       9.00       3.56      12.67
33115           119000      25.75       6.02      13.75       2.05      16.00
33116           119250      31.50       3.35      10.25       5.12      16.25
33117           119500      33.75       2.77      14.00       3.24      13.75
33118           119750      37.00       1.41      18.25       3.70      11.00

       var_rss23
0           0.00
1           1.09
2           0.00
3           0.00
4           0.43
...          ...
33114       4.19
33115       1.58
33116       2.95
33117       0.43
33118       4.32

[33119 rows x 7 columns]

testData and trainData have the testing and training dataset

(c)Feature Extraction

(i)Research what types of time-domain features are usually used in time series
classification and list them (examples are minimum, maximum, mean, etc).

Mean       
Median           
Standard Deviation          
Variance           
Minimum             
Maximum            
Cross Correlation             
Auto Correlation              
Moving Average            

Ref: https://stats.stackexchange.com/questions/50807/features-for-time-series-classification

(ii)Extract the time-domain features minimum, maximum, mean, median, standard
deviation, first quartile, and third quartile for all of the 6 time series
in each instance

In [3]:
time_series=['avg_rss12','var_rss12','avg_rss13','var_rss13','avg_rss23','var_rss23']
time_features=['min','max','mean','median','std dev','1st quart','3rd quart']
all_features=list()


def extract_feature(num,activity):
    Actual_features=['min','max','mean','50%','std','25%','75%']
    features=list()
    global num_of_instance
    for i in range(1,num+1):
        pathToChoose='../data/AReM/'+activity+'/dataset'+str(i)+'.csv'
        df=pd.read_csv(pathToChoose, usecols=range(7), skiprows = 4)
        local_stats=[num_of_instance]
        for col_name in time_series:
            for f in Actual_features:
               local_stats.append(df.describe()[col_name][f])
        features.append(local_stats)
        num_of_instance=num_of_instance+1
    return features
        
num_of_instance=1
f1=extract_feature(7,'bending1')
f2=extract_feature(6,'bending2')
f3=extract_feature(15,'cycling')
f4=extract_feature(15,'lying')
f5=extract_feature(15,'sitting')
f6=extract_feature(15,'standing')
f7=extract_feature(15,'walking')

all_features.extend(f1)
all_features.extend(f2)
all_features.extend(f3)
all_features.extend(f4)
all_features.extend(f5)
all_features.extend(f6)
all_features.extend(f7)


columns_disp=list()
columns_disp.append('Instance')
num_of_timeseries=[1,2,3,4,5,6]
for num in num_of_timeseries:
    for t in time_features:
        columns_disp.append(t+str(num))

final_table=pd.DataFrame(all_features, columns=columns_disp)
display(final_table)

,Instance,min1,max1,mean1,median1,std dev1,1st quart1,3rd quart1,min2,max2,...,std dev5,1st quart5,3rd quart5,min6,max6,mean6,median6,std dev6,1st quart6,3rd quart6
0,1,37.25,45.00,40.624792,40.50,1.476967,39.25,42.0000,0.0,1.30,...,2.188449,33.0000,36.00,0.00,1.92,0.570583,0.43,0.582915,0.0000,1.3000
1,2,38.00,45.67,42.812812,42.50,1.435550,42.00,43.6700,0.0,1.22,...,1.995255,32.0000,34.50,0.00,3.11,0.571083,0.43,0.601010,0.0000,1.3000
2,3,35.00,47.40,43.954500,44.33,1.558835,43.00,45.0000,0.0,1.70,...,1.999604,35.3625,36.50,0.00,1.79,0.493292,0.43,0.513506,0.0000,0.9400
3,4,33.00,47.75,42.179812,43.50,3.670666,39.15,45.0000,0.0,3.00,...,3.849448,30.4575,36.33,0.00,2.18,0.613521,0.50,0.524317,0.0000,1.0000
4,5,33.00,45.75,41.678063,41.75,2.243490,41.33,42.7500,0.0,2.83,...,2.411026,28.4575,31.25,0.00,1.79,0.383292,0.43,0.389164,0.0000,0.5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,84,19.50,45.33,33.586875,34.25,4.650935,30.25,37.0000,0.0,14.67,...,3.283983,13.7300,18.25,0.00,8.32,3.259729,3.11,1.640243,2.0500,4.3225
84,85,19.75,45.50,34.322750,35.25,4.752477,31.00,38.0000,0.0,13.47,...,3.119856,13.5000,17.75,0.00,9.67,3.432563,3.20,1.732727,2.1575,4.5650
85,86,19.50,46.00,34.546229,35.25,4.842294,31.25,37.8125,0.0,12.47,...,2.823124,14.0000,17.75,0.00,10.00,3.338125,3.08,1.656742,2.1600,4.3350
86,87,23.50,46.25,34.873229,35.25,4.531720,31.75,38.2500,0.0,14.82,...,3.131076,13.7500,18.00,0.00,9.51,3.424646,3.27,1.690960,2.1700,4.5000
87,88,19.25,44.00,34.473188,35.00,4.796705,31.25,38.0000,0.0,13.86,...,3.156320,13.7300,17.75,0.43,9.00,3.340458,3.09,1.699114,2.1200,4.3750

(iii)Estimate the standard deviation of each of the time-domain features you
extracted from the data. Then, use Python's bootstrapped or any other
method to build a 90% bootsrap confidence interval for the standard deviation
of each feature.

In [4]:
only_data_columns=final_table.drop('Instance',axis=1)
all_std=only_data_columns.std()
display(all_std)

min1          9.569975
max1          4.394362
mean1         5.335718
median1       5.440054
std dev1      1.772153
1st quart1    6.153590
3rd quart1    5.138925
min2          0.000000
max2          5.062729
mean2         1.574164
median2       1.412244
std dev2      0.884105
1st quart2    0.946386
3rd quart2    2.125266
min3          2.956462
max3          4.875137
mean3         4.008380
median3       4.036396
std dev3      0.946710
1st quart3    4.220658
3rd quart3    4.171628
min4          0.000000
max4          2.183625
mean4         1.166114
median4       1.145586
std dev4      0.458242
1st quart4    0.843620
3rd quart4    1.552504
min5          6.124001
max5          5.741238
mean5         5.675593
median5       5.813782
std dev5      1.024898
1st quart5    6.096465
3rd quart5    5.531720
min6          0.045838
max6          2.518921
mean6         1.154812
median6       1.086474
std dev6      0.517617
1st quart6    0.758584
3rd quart6    1.523599
dtype: float64

In [5]:
data_for_bootstrap=(only_data_columns, )

In [6]:
conf_int=bootstrap(data_for_bootstrap, np.std, confidence_level=0.9, method='basic')
low_high_interval=conf_int.confidence_interval
print(low_high_interval)

ConfidenceInterval(low=array([8.32045863, 3.48600639, 4.76849643, 4.85309158, 1.58439549,
       5.62811653, 4.42450832, 0.        , 4.69543931, 1.43397865,
       1.27217428, 0.82238918, 0.85274368, 1.94387235, 2.78640923,
       4.2625757 , 3.50761495, 3.51543612, 0.76661969, 3.7174666 ,
       3.63447654, 0.        , 1.99454051, 1.10333811, 1.08313072,
       0.42756469, 0.79092024, 1.46911508, 4.69550298, 4.8800933 ,
       4.57867142, 4.67000108, 0.82953528, 4.94472136, 4.48498688,
       0.01312496, 2.26211831, 1.08813154, 1.01838566, 0.48727412,
       0.70426456, 1.43754451]), high=array([10.82969588,  5.40852846,  5.9315742 ,  6.04681977,  1.96011702,
        6.69881022,  5.90516807,  0.        ,  5.48004394,  1.74430618,
        1.57873616,  0.96198942,  1.05693714,  2.34600614,  3.13590995,
        5.54205533,  4.57539532,  4.61748229,  1.12525637,  4.78970323,
        4.77547897,  0.        ,  2.38152708,  1.25278029,  1.23157238,
        0.49298139,  0.90946499,  1.66762771,  7.75167918,  6.68845554,
        6.90153098,  7.08170417,  1.231555  ,  7.35836336,  6.6761065 ,
        0.09115393,  2.77142297,  1.24250409,  1.17339563,  0.5540739 ,
        0.82339393,  1.6385673 ]))

In [7]:
Confidence_Interval_Table=list()

for i in range(1,len(columns_disp)):
    each_item=[columns_disp[i],low_high_interval[0][i-1],low_high_interval[1][i-1]]
    Confidence_Interval_Table.append(each_item)

col_disp=['feature','Interval_start','Interval_end']
final_Conf_Int=pd.DataFrame(Confidence_Interval_Table,columns=col_disp)
display(final_Conf_Int)

       feature  Interval_start  Interval_end
0         min1        8.320459     10.829696
1         max1        3.486006      5.408528
2        mean1        4.768496      5.931574
3      median1        4.853092      6.046820
4     std dev1        1.584395      1.960117
5   1st quart1        5.628117      6.698810
6   3rd quart1        4.424508      5.905168
7         min2        0.000000      0.000000
8         max2        4.695439      5.480044
9        mean2        1.433979      1.744306
10     median2        1.272174      1.578736
11    std dev2        0.822389      0.961989
12  1st quart2        0.852744      1.056937
13  3rd quart2        1.943872      2.346006
14        min3        2.786409      3.135910
15        max3        4.262576      5.542055
16       mean3        3.507615      4.575395
17     median3        3.515436      4.617482
18    std dev3        0.766620      1.125256
19  1st quart3        3.717467      4.789703
20  3rd quart3        3.634477      4.775479
21        min4        0.000000      0.000000
22        max4        1.994541      2.381527
23       mean4        1.103338      1.252780
24     median4        1.083131      1.231572
25    std dev4        0.427565      0.492981
26  1st quart4        0.790920      0.909465
27  3rd quart4        1.469115      1.667628
28        min5        4.695503      7.751679
29        max5        4.880093      6.688456
30       mean5        4.578671      6.901531
31     median5        4.670001      7.081704
32    std dev5        0.829535      1.231555
33  1st quart5        4.944721      7.358363
34  3rd quart5        4.484987      6.676107
35        min6        0.013125      0.091154
36        max6        2.262118      2.771423
37       mean6        1.088132      1.242504
38     median6        1.018386      1.173396
39    std dev6        0.487274      0.554074
40  1st quart6        0.704265      0.823394
41  3rd quart6        1.437545      1.638567

iv)Use your judgement to select the three most important time-domain features

**It can be mean, median and standard deviation- which has a low range in the CI.**

2.ISLR3.7.4

(a)**Training RSS for cubic regression would be lower as the data will fit better(or even tend to overfit) as when compared to training RSS for linear regression**

(b)**Test RSS for linear regression would be lower as it is the true relationship as when compared to test RSS for cubic regression which is an overfit**

(c)**Since the relationship is not linear, the cubic regression will fit the data better, leading to lower training RSS as when compared to training RSS for linear regression**

(d) **It depends on the true relationship, if it is closer to cubic relationship then test RSS for cubic regression would be lower, if it is closer to the linear relationship than cubic relationship then test RSS for linear regression would be lower.**